# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('attDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Attendance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.TextField()),
            ],
            options={
                'db_table': 'Modules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('form', models.IntegerField()),
                ('Class', models.CharField(max_length=5)),
                ('image', models.TextField(max_length=100)),
                ('GPA', models.FloatField()),
                ('address', models.TextField(max_length=100)),
                ('discipline_record', models.TextField(max_length=100)),
                ('feedback', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Teacher',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='modules',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classapp.Student'),
        ),
    ]
