# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.TextField(default='No Name Provided', max_length=30),
        ),
    ]
