# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_teacher_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='discipline_record',
            new_name='discipleRecord',
        ),
    ]
