# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0005_auto_20160411_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='id',
        ),
        migrations.AlterField(
            model_name='modules',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classapp.Student'),
        ),
    ]
