# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0006_auto_20160412_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='modules',
            field=models.TextField(default=' ', max_length=300),
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
