# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0007_auto_20160412_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.TextField(max_length=10),
        ),
    ]
