# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0008_auto_20160412_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
