# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0010_auto_20160412_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comments',
            field=models.TextField(default=' ', max_length=200),
        ),
    ]
